repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        name: Ensure commits are only made to feature branches
        args: ['-b', 'main']
      - id: end-of-file-fixer
        name: Ensure files have end of file
      - id: trailing-whitespace
        name: Trims extra whitespaces
      - id: check-toml
        name: Checks TOML files
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
        name: Yaml Formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.3
    hooks:
      - id: terraform_fmt
        name: Terraform FMT
      - id: terragrunt_fmt
        name: Terragrunt FMT
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-github-actions
        name: GitHub actions check
      - id: check-dependabot
        name: GitHub Workflows
      - id: check-dependabot
        name: Dependabot
      - id: check-jsonschema
        name: Validate markdown lint file
        files: .github/config/.markdownlint.yaml
        args: ["--schemafile", "https://raw.githubusercontent.com/DavidAnson/markdownlint/refs/heads/main/schema/markdownlint-config-schema.json"]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.1
    hooks:
      - id: markdownlint-cli2
        args: ["--config", "./.github/config/.markdownlint.yaml", "--fix"]
