version: 3

tasks:
  default:
    desc: Lists the available commands
    cmds:
      - task --list-all
  serve:
    desc: Runs mkdocs serve
    cmds:
      - mkdocs serve
  dirty:
    desc: Runs mkdocs dirty reload
    cmds:
      - mkdocs serve --dirtyreload
  build:
    desc: Builds the site
    cmds:
      - mkdocs build
  md-lint:
    desc: Lints the README.md file and suggests changes you can make
    silent: true
    ignore_error: true
    cmds:
      - vale README.md