"$schema": https://raw.githubusercontent.com/DavidAnson/markdownlint/refs/heads/main/schema/markdownlint-config-schema.json
no-inline-html:
  allowed_elements:
    - img
    - svg
    - ul
    - li
    - text
    - path
    - g
    - country
    - area
    - dcnumber
    - u
    - user
    - password
    - url
    - email
    - nickname
    - description
    - role
    - field
    - value
    - yyyy-mm-dd-hh-ii-ss
    - brand
    - sup
    - atx
    - name
    - zone
    - destination
    - project-name
    - container
    - tag
    - KEY
    - br
    - tenant
    - style
    - body
    - input
    - label
    - script
    - textarea
code-block-style: false
fenced-code-language: false
no-alt-text: false
list-indent: false
heading-increment: false
no-duplicate-heading: false
first-line-heading: false
heading-style:
  style: atx
descriptive-link-text: false #todo: Fix this at some point
ul-indent: false
line-length: false
no-emphasis-as-heading: false
