name: Broken Link Checker PR
on:
  pull_request:
    types:
      - synchronize
      - opened
    paths:
      - docs/**
      - .github/workflows/broken-link-checker-pr.yaml
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Links
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst' --exclude-mail
          output: /tmp/out.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: PR comment with Broken Links
        if: env.lychee_exit_code != 0
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          filePath: /tmp/out.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
