name: Codespell
on:
  pull_request:
    paths:
      - docs/**
jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47.0.0
      - uses: codespell-project/actions-codespell@v2
        with:
          # Exit with 0 regardless of typos.
          only_warn: 1
          path: ${{ steps.changed-files.outputs.all_changed_files }}
