name: Production Nightly Build
on:
  schedule:
    - cron: 20 4 * * *
  workflow_dispatch:
jobs:
  site:
    runs-on: ubuntu-latest
    name: Build Documentation
    environment:
      name: Production
      url: https://documentation.breadnet.co.uk
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fly Build and Deploy
        uses: userbradley/actions-fly@v1.1.0
        with:
          flyToken: ${{ secrets.FLY_ACCESS_TOKEN_PROD }}
          configFile: ${{ vars.CONFIG_FILE }}
  open-issue:
    runs-on: ubuntu-latest
    name: Open GitHub issue on failure
    if: failure()
    needs: [site]
    steps:
      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5.0.1
        with:
          title: Nightly build failed
          labels: Broken Nightly Build
