on:
  workflow_dispatch:
name: Runs on failure
jobs:
  should-fail:
    runs-on: ubuntu-latest
    name: Failure
    steps:
      - name: Fail
        run: exit 1
  run-when-fail:
    runs-on: ubuntu-latest
    name: Runs when it fails
    needs: [should-fail]
    if: failure()
    steps:
      - name: test
        run: echo "hello"
